export const USER_OTP_REQUEST = 'USER_OTP_REQUEST';
export const USER_OTP_SUCCESS = 'USER_OTP_SUCCESS';
export const USER_OTP_FALIURE = 'USER_OTP_FALIURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FALIURE = 'USER_LOGIN_FALIURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';